hw05: Parallel execution
sedovandrew/hw-golang pull request #12
Opened 2022-12-04 14:26 UTC by sedovandrew

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-04 14:46 UTC, dshemin requested changes

2022-12-04 14:46 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	taskCh := make(chan Task)
Критично:

Нет проверки на границы `n` и `m`. Ответьте на вопросы:

- Что будет если `n` равно 0 или меньше
- Что будет если `m` равно 0 или меньше

2022-12-04 14:46 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	errCh := make(chan int)
Совет:

Тут мы в errCh просто записываем 1, по факту нам значение не нужно. В таких случаях будет лучше использовать тип `struct{}` он не будет занимать память.

Но более того, согласно коду дальше, вы организовали счётчик. Для этого лучше подойдёт либо интовое поле с mutex или, более предпочтительный вариант, использовать atomic.

2022-12-04 14:46 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	for range errCh {
Критично:

В этом цикле нет проверки на количество ошибок. Представьте такую ситуацию:
Дано:
- У нас 5 задач
- n = 5
- m = 2

Каждая из задач работает долго. Таким образом мы пролетаем цикл на строках 40-51 до того как хотя бы одна из них завершится. Они все начинают завершатся с ошибками.

Правильно ли мы обработаем такую ситуацию?

2022-12-04 14:46 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	go func() {
Совет:

Нет необходимости запускать этот код в горутне. Достаточно передвинуть блок
```
wg.Wait()
close(errCh)
```

После:
```
close(taskCh)
```

2022-12-05 09:28 UTC, sedovandrew commented on hw05_parallel_execution/run.go
> +	taskCh := make(chan Task)
Переработал решение. Добавил тесты.

2022-12-05 09:28 UTC, sedovandrew commented on hw05_parallel_execution/run.go
> +	errCh := make(chan int)
В новом решении отказался от данного канала совсем в пользу atomic счётчика.

2022-12-05 09:29 UTC, sedovandrew commented on hw05_parallel_execution/run.go
> +	for range errCh {
В новом решении всё совсем по другому.

2022-12-05 09:29 UTC, sedovandrew commented on hw05_parallel_execution/run.go
> +	go func() {
Создание worker-ов вынес из горутины.

2022-12-05 16:17 UTC, dshemin approved these changes

2022-12-06 04:10 UTC, merged